# Generated by Django 3.1.4 on 2021-02-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenmanager',
            name='url',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
